<?php

namespace AppBundle\Repository;

/**
 * SessionRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class SessionRepository extends \Doctrine\ORM\EntityRepository
{

    /**
     *
     */
    public function findBySessionId($value, $userId){

        $return = $this->getEntityManager()
            ->createQuery(
                "SELECT session FROM AppBundle:Session session  WHERE session.sessionId = :value and session.user = :userId "
            )
            ->setParameter( 'value', "$value")
            ->setParameter( 'userId', "$userId")
            ->getResult();

        return $return;

    }

    public function findAcSession($userId){

        $return = $this->getEntityManager()
            ->createQuery(
                "SELECT session FROM AppBundle:Session session  WHERE session.user = :userId "
            )
            ->setParameter( 'userId', "$userId")
            ->getResult();

        return $return;

    }

    public function DeleteById($value){

        $return = $this->getEntityManager()
            ->createQuery(
                "DELETE FROM AppBundle:Session session WHERE session.sessionId = :value "
            )
            ->setParameter( 'value', "$value")
            ->getResult();

        return $return;

    }

}
